
services:
  bigdata-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: bigdata-project-master
    
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    hostname: hadoop-master
    tty: true
    networks:
      - bigdataProject
      - bigdata-mongo
  bigdata-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: bigdata-project-slave1
    ports:
      - "8040:8042"
    hostname: hadoop-slave1
    tty: true
    networks:
      - bigdataProject

  bigdata-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: bigdata-project-slave2
    ports:
      - "8041:8042"
    hostname: hadoop-slave2
    tty: true
    networks:
      - bigdataProject
  
  bigdata-mongo:
    build : 
      context: ./mongo/config
    container_name: bigdata-project-mongo-container
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: racem
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
      - 9042:9042
  
    networks:
      - bigdata-mongo
    entrypoint:
     - bash
     - -c
     - exec docker-entrypoint.sh $$@ 
    command: mongod   --keyFile data/replica.key  --replSet rs0 --bind_ip 127.0.0.1,mongo
  bigdata-mongo-express:
    image: mongo-express
    container_name: bigdata-project-mongo-express-container
    hostname: mongo-express
    ports:
      - "8081:8081"
    networks:
      - bigdata-mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: racem
      ME_CONFIG_MONGODB_URL: mongodb://root:racem@mongo:27017/?authSource=admin&replicaSet=rs0
      

    restart: unless-stopped
  
  bigdata-visualization-backend:
    container_name: bigdata-visualization-backend
    build:
      context: ./visualization/backend
    ports:
      - "3000:3000"
    networks:
      - bigdata-mongo
      - bigdata-viz
      - bigdataProjectBatch

    environment:
      DATABASE_URI : mongodb://root:racem@mongo:27017/airline?authSource=admin&replicaSet=rs0&retryWrites=false
      PORT : 3000
    command: npm run start
    depends_on:
      - bigdata-mongo
  
  batch-bigdata-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: batch-bigdata-project-master
    
    ports:
      - "50071:50070"
      - "8089:8088"
      - "7078:7077"
      - "16011:16010"
    hostname: hadoop-master
    tty: true
    networks:
      - bigdataProjectBatch
  batch-bigdata-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: batch-bigdata-project-slave1
    ports:
      - "8045:8042"
    hostname: hadoop-slave1
    tty: true
    networks:
      - bigdataProjectBatch

  batch-bigdata-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: batch-bigdata-project-slave2
    ports:
      - "8046:8042"
    hostname: hadoop-slave2
    tty: true
    networks:
      - bigdataProjectBatch

networks:
  bigdataProject : {}
  bigdata-mongo : {}
  bigdata-viz : {}
  bigdataProjectBatch : {}
  
  

